apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lms-kiosk-frontend
  namespace: lms
  labels:
    app: lms-kiosk-frontend
spec:
  serviceName: lms-kiosk-frontend
  replicas: 1
  selector:
    matchLabels:
      app: lms-kiosk-frontend
  template:
    metadata:
      labels:
        app: lms-kiosk-frontend
    spec:
      containers:
        - name: lms-kiosk-frontend
          image: devlaundromat/lms-frontend:20251011_115740_aef04db
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"


