apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lms-backend-tls
  namespace: lms
spec:
  secretName: lms-backend-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: api.washgo247.com
  dnsNames:
    - api.washgo247.com
  duration: 2160h
  renewBefore: 360h


