apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lms-kiosk-frontend-ingress
  namespace: lms
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - kiosk.washgo247.com
    secretName: kiosk-washgo247-com-tls
  rules:
  - host: kiosk.washgo247.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lms-kiosk-frontend-clusterip
            port:
              number: 80


