apiVersion: v1
kind: Service
metadata:
  name: lms-portal-frontend-clusterip
  namespace: lms
  labels:
    app: lms-portal-frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: lms-portal-frontend
