apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-db-init
  namespace: harbor
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: psql
          image: postgres:15
          imagePullPolicy: IfNotPresent
          env:
            - name: PGHOST
              value: postgres-clusterip.database.svc.cluster.local
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: "washgo247.admin"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-db-secret
                  key: password
          command:
            - /bin/sh
            - -c
          args:
            - >-
              psql "postgresql://$PGUSER:$PGPASSWORD@$PGHOST:$PGPORT/postgres" -v ON_ERROR_STOP=1 -q -t -c
              "SELECT 'CREATE DATABASE harbor' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'harbor')\n\gexec" &&
              echo "Database harbor is present."


