apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lms-celery-worker
  namespace: lms
  labels:
    app: lms-celery-worker
spec:
  serviceName: lms-celery-worker
  replicas: 2
  selector:
    matchLabels:
      app: lms-celery-worker
  template:
    metadata:
      labels:
        app: lms-celery-worker
    spec:
      containers:
        - name: lms-celery-worker
          image: devlaundromat/lms-celery-worker_production:20251013_153506_5686824
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: lms-backend-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"


