apiVersion: v1
kind: Service
metadata:
  name: lms-backend-clusterip
  namespace: lms
  labels:
    app: lms-backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: lms-backend


