apiVersion: v1
kind: Service
metadata:
  name: lms-backend-nodeport
  namespace: lms
  labels:
    app: lms-backend
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30200
      protocol: TCP
  selector:
    app: lms-backend


