apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rancher-registry
  namespace: registry
  labels:
    app: rancher-registry
spec:
  serviceName: rancher-registry
  replicas: 1
  selector:
    matchLabels:
      app: rancher-registry
  template:
    metadata:
      labels:
        app: rancher-registry
    spec:
      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: IfNotPresent
          env:
            - name: REGISTRY_HTTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: rancher-registry-secret
                  key: REGISTRY_HTTP_SECRET
          ports:
            - containerPort: 5000
              name: registry
          volumeMounts:
            - name: registry-config
              mountPath: /etc/docker/registry
            - name: registry-data
              mountPath: /var/lib/registry
      volumes:
        - name: registry-config
          configMap:
            name: rancher-registry-config
            items:
              - key: config.yml
                path: config.yml
        - name: registry-data
          hostPath:
            path: /data/rancher-registry
            type: DirectoryOrCreate


