apiVersion: v1
kind: Service
metadata:
  name: mosquitto-nodeport
  namespace: mosquito-mqtt
  labels:
    app: mosquitto
spec:
  type: NodePort
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      nodePort: 30101
  selector:
    app: mosquitto


